#!/bin/bash

# Setup function which re-creates the values and keys when written along with
# getting initial values
setup(){
  keys=("TARGET_DEVICE" "TARGET_PWD" "TARGET_APK" 
        "TARGET_BUILD" "TARGET_PACKAGE" )
  values=("$TARGET_DEVICE" "$TARGET_PWD" "$TARGET_APK" 
          "$TARGET_BUILD" "$TARGET_PACKAGE" )
  size=5;
}
# Commands
processCommands(){
  # Delete package from device
  if [ "$1" == "delete" ]
  then
    checkValid "$TARGET_DEVICE"
    if [ $? = 1  ] ; then
    echo "Removing $TARGET_PACKAGE from $TARGET_DEVICE"
    adb -s $TARGET_DEVICE uninstall $TARGET_PACKAGE; fi
  fi

  # Install package to device
  if [ "$1" == "install" ]
  then
    checkValid "$TARGET_DEVICE"
    if [ $? == 1  ] ; then
      echo "Install $TARGET_APK  to $TARGET_DEVICE"
      adb -s $TARGET_DEVICE install -r $TARGET_APK
    fi
  fi

  # Build the application
  if [ "$1" == "build" ]
  then
    # Pass the build folder to the build function
    checkValid "$TARGET_BUILD"
    if [ "$?" == 1 ] ; then
      echo "$DIR/$TARGET_BUILD"
      . $DIR/$TARGET_BUILD
      buildfile "$TARGET_PWD"
    fi
  fi

  # Update the device ID
  if [ "$1" == "setdev" ]
  then
    echo "Please Enter Device"
    read -a TARGET_DEVICE
  fi

  # Update the location of the source
  if [ "$1" == "setloc" ]
  then
    echo "Please Enter full Location path"
    read -a TARGET_PWD
    echo "Target Directory: $TARGET_PWD"
  fi

  if [ "$1" == "setapk" ]
  then
    echo "Enter path to APK"
    read -a TARGET_APK
    echo "Target APK: $TARGET_APK"
  fi


  # Output the varaibles 
  if [ "$1" == "echo" ]
  then
    # Do a write so that the files are listed 
    writeProperties "$keys" "$values" "$size" "$PROPS"
    setup
    echoProperties "$keys" "$values" "$size"
  fi
  
  # Set the build file to query
  if [ "$1" == "setbuild" ]
  then
     echo "Enter build target"
     # Perhaps adding a list of build targets?
     read -a TARGET_BUILD
  fi

  if [ "$1" == "setpack" ]
  then
    echo "Enter Package: "
    read -a TARGET_PACKAGE
  fi

  # Send the targeted APK to the device
  if [ "$1" == "sendApk" ] 
  then
    # Check that the variables are set before attempting
    checkValid "$TARGET_DEVICE"
    if [ $? == 1  ] ; then
      echo "Sending APK to $TARGET_DEVICE"
      adb -s $TARGET_DEVICE install -r $TARGET_APK 
    fi
  fi
}

# Pull the location of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Location of the properties file which stores all values needed
PROPS="$DIR/values.properties"

# Pull in the values in the file
. $PROPS

# Load the functions needed
. $DIR/lib


# Hard coded variables
# TODO find a way to automate this
setup
for var in "$@"
do
    processCommands "$var"
done
setup
# Persist the variables
writeProperties "$keys" "$values" "$size" "$PROPS"
